packages/openssh/SPECS/openssh.spec
`useradd` isn't present in IRIX, so the rpm won't want to install as it doesn't exist. Furthermore, let's use IRIX's `addUserAccount` to create the privilege separation user.
=> Remove useradd requirement and use addUserAccount

packages/chkconfig/SPECS/chkconfig.spec, packages/elfutils/SPECS/elfutils.spec, packages/libdicl/SPECS/libdicl.spec, packages/libtasn1/SPECS/libtasn1.spec, packages/p11-kit/SPECS/p11-kit.spec, packages/popt/SPECS/popt.spec, packages/rpm/SPECS/rpm.spec
The upgrade to 0.1.19 of libdicl includes a fix so that no downgrade/upgrade dance is needed - all packages that depend on it can now be built against this newer version.
This pull request include the libdicl version change - but also a version bump and mandated minimum version of the things that _use_ libdicl.
The order to build and upgrade (do the install after each individual build) of these is:
libdicl
chkconfig (but only install the `alternatives` output RPM)
libtasn1
p11-kit
popt
elfutils
rpm
The upgrade in this pull request is needed for the merge of pcre.
=> Upgrade of libdicl to 0.1.19 for strto* functionality

packages/desktop-file-utils/SOURCES/desktop-file-utils.irixfixes.patch, packages/desktop-file-utils/SPECS/desktop-file-utils.spec
From prior PR, you'd said: 
> (1) This pull request is trying to merge to master
> (2) This pull request has oodles of fluff on it
> (3) desktop-file-utils isn't applicable for us - irix doesn't support xdg-desktop protocols - we do need an equivalent - but I think it's not this package.
I resolved 1. Not sure about 2. 
Re 3, desktop-file-utils is a dep for many things. What's better, to comment out the dependency, or to add this dependency's package knowing it'll not be used?
It seems safer to add this package now even though nothing can use it. If there's any chance we can get xdg to work with IRIX at some point, this will save us having to uncomment the dep in thousands (ha!) of specs.
=> added desktop-file-utils

packages/cmake/SOURCES/cmake.sgifixeslibuv.patch, packages/cmake/SPECS/cmake.spec, packages/jsoncpp/SPECS/jsoncpp.spec, packages/libuv/SOURCES/libuv.sgifixes.patch, packages/libuv/SPECS/libuv.spec
Fix up the cmake install libdir to be lib32 and pull some sgug libuv fixes + stability tweaks.
jsoncpp now doesn't have the library directory work around.
=> cmake, libuv, jsoncpp

packages/icu/SOURCES/exclude-burmese.patch, packages/icu/SPECS/icu.spec
Our builds are now dying because of [an issue with the Burmese locales](https://gist.github.com/mach-kernel/edb0cbf54aee32d29fcfa4c19277a538) ??
Using another machine [and the instructions for the ICU build tools here](https://github.com/unicode-org/icu/blob/master/docs/userguide/icu_data/buildtool.md), I generated another `icudt67l.dat` file that filters on `en*` only.
=> ICU4C: Provide filtered ICU dat file

packages/gdk-pixbuf2/SOURCES/gdkpixbuf4.irixfixes.patch, packages/gdk-pixbuf2/SPECS/gdk-pixbuf2.spec
It looks like gdk-pixbuf is responsible for generating `loaders.cache`:
```
build-aux/post-install.sh:9:        $bindir/gdk-pixbuf-query-loaders-32 > "$libdir/gdk-pixbuf-2.0/$binary_version/loaders.cache"
```
Ended up dropping the patch for the `build-aux` script altogether and running the gen command from the spec, to preserve the `isa-bits` functionality which would not have been provided by `postinstall.sh`
=> gdk-pixbuf2 fix postinstall loader cache issues

packages/gtk2/SPECS/gtk2.spec
Changes:
- `rm` generated libtool from builddir and copy ours from `/usr/sgug/bin` (is there a better way? `autoreconf` did not work)
- Replace case statement with `%{_isa_bits}`
- Update `gtk-builder-convert` Python to point to `/usr/sgug/bin/python`
- There are now some extra `.a` files that are produced with our libtool -- will deleting these break anything?
[Build log](https://gist.github.com/mach-kernel/3a3bc8ccd54d12002536b6b4a434ea09)
Install log:
```
[sgugshell mach@octane SPECS]$ sudo rpm -ivh ~/rpmbuild/RPMS/mips/gtk2*.rpm
1:gtk2-2.24.32-5.sgugbeta          ################################# [ 25%] …
```
=> gtk2: fix libtool wrapper issue, missing immodules query

packages/hunspell-en/SOURCES/en_GB-singleletters.patch, packages/hunspell-en/SOURCES/en_GB.etc.patch, packages/hunspell-en/SOURCES/en_GB.two_initial_caps.patch, packages/hunspell-en/SOURCES/en_IE.supplemental.patch, packages/hunspell-en/SOURCES/en_US-strippedabbrevs.patch, packages/hunspell-en/SOURCES/hunspell-en-SI_and_IEC.patch, packages/hunspell-en/SOURCES/hunspell-en-allow-non-typographical.marks.patch, packages/hunspell-en/SOURCES/hunspell-en-calender.patch, packages/hunspell-en/SOURCES/hunspell-en-dont-call-git-during-build.patch, packages/hunspell-en/SOURCES/hunspell-en-fixbuild.patch, packages/hunspell-en/SOURCES/hunspell-en-irregular-plural-possessive.patch, packages/hunspell-en/SOURCES/mozilla_words.patch, packages/hunspell-en/SOURCES/perl.regex.patch, packages/hunspell-en/SPECS/hunspell-en.spec
Forgot to get a build log before turning it off, updated the Perl path and it seems to work fine.
```
[sgugshell mach@octane SPECS]$ sudo rpm -ivh ~/rpmbuild/RPMS/noarch/hunspell-en-* ~/rpmbuild/RPMS/mips/hunspell-*
1:hunspell-en-GB-0.20140811.1-16.sg################################# [ 20%]
2:hunspell-en-US-0.20140811.1-16.sg################################# [ 40%]
3:hunspell-1.7.0-3.sgugbeta        ################################# [ 60%]
4:hunspell-en-0.20140811.1-16.sgugb################################# [ 80%]
5:hunspell-devel-1.7.0-3.sgugbeta  ################################# [100%]
```
=> Add hunspell-en

packages/gnutls/SPECS/gnutls.spec
[Build log](https://gist.github.com/mach-kernel/e81e043f659917c67a32947575c6071d)
```
[sgugshell mach@octane SPECS]$ sudo rpm -ivh ~/rpmbuild/RPMS/mips/gnutls-*
1:gnutls-3.6.14-1.sgugbeta         ################################# [ 25%]
2:gnutls-utils-3.6.14-1.sgugbeta   ################################# [ 50%]
3:gnutls-c++-3.6.14-1.sgugbeta     ################################# [ 75%]
4:gnutls-devel-3.6.14-1.sgugbeta   ################################# [100%]
```
=> gnutls: fixes for working with no-docs

packages/gnutls/SPECS/gnutls.spec
```
[sgugshell mach@octane SPECS]$ sudo rpm -ivh ~/rpmbuild/RPMS/mips/gnutls-* --nodeps
1:gnutls-3.6.14-1.sgugbeta         ################################# [ 25%]
2:gnutls-c++-3.6.14-1.sgugbeta     ################################# [ 50%]
3:gnutls-devel-3.6.14-1.sgugbeta   ################################# [ 75%]
4:gnutls-utils-3.6.14-1.sgugbeta   ################################# [100%]
[sgugshell mach@octane SPECS]$ certtool
certtool [options]
certtool --help for usage instructions.
[sgugshell mach@octane SPECS]$ certtool --version
certtool 3.6.14
Copyright (C) 2000-2020 Free Software Foundation, and …
```
=> gnutls: fix libtool wrapper scripts

packages/nettle/SPECS/nettle.spec, packages/shared-mime-info/SPECS/shared-mime-info.spec
shared-mime-info: Re-seen the "mime lookup cache" not created on install. A little tweak (force the compute of the cache on install) is a simple short term solution that avoids the need to re-install.
nettle: prior to 0.0.6 things had dependencies on the older version of the nettle library -> now everything is rebuilt for 0.0.6, we can retire the old compatiblity library (the regular nettle library is still there).
=> 0.0.6 - Bug fix (shared-mime-info) and old lib retirement (nettle)

packages/fontconfig/SPECS/fontconfig.spec, packages/purple-discord/SPECS/purple-discord.spec, packages/purple-discord/SPECS/purple-discord.spec.origfedora
Include original fedora spec, fix up fontconfig to better generate the font cache and include the missing pidgin-discord images via tarball.
The needed tarball can be found under the sgug-rse releases tab, under 0.0.6pre.
=> More purple-discord tweaks for 0.0.6

packages/docbook5-style-xsl/SPECS/docbook5-style-xsl.spec, packages/gobject-introspection/SPECS/gobject-introspection.spec, packages/pax-utils/SPECS/pax-utils.spec, packages/rpm/SPECS/rpm.spec, packages/sgug-rpm-config/SOURCES/sgug-etc-rpm-macros, packages/sgug-rpm-config/SPECS/sgug-rpm-config.spec, releasepackages.lst
During world build one, a few packages became broken due to macro changes, plus add the missing `worker` entry in releasepackages.txt.
=> Release 0.0.6 - Fixes discovered during world build #1

packages/chrpath/SPECS/chrpath.spec
Resolves #145 
Updated the spec to symlink to `/usr/sgug/bin/true`. 
```
[sgugshell mach@octane SPECS]$ rpmbuild --clean -ba chrpath.spec
warning: Macro expanded in comment on line 9: %{version}/chrpath-%{version}.tar.gz
warning: Macro expanded in comment on line 22: %{_includedir}/libdicl-0.1"
warning: Macro expanded in comment on line 24: %configure
warning: Macro expanded in comment on line 25: %make_build
warning: Macro expanded in comment on line 37: %{_mandir}/man1/chrpath.1*
Executing(%install): /usr/sgug/bin/sh -e /usr/sgug/var/tmp/rpm-tmp.001414
+ umask 022
+ cd /usr/people/mach/rpmbuild/BUILD
+ mkdir -p /usr/people/mach/rpmbuild/BUILDROOT/chrpath-0.16-14.sgug.mips/usr/sgug/bin
+ ln -s /usr/sgug/bin/true /usr/people/mach/rpmbuild/BUILDROOT/chrpath-0.16-14.sgug.mips/usr/sgug/bin/ch …
```
=> Make chrpath do nothing

packages/gtk3/SPECS/gtk3.spec, packages/publicsuffix-list/SPECS/publicsuffix-list.spec, packages/sgug-rpm-tools/SPECS/sgug-rpm-tools.spec, packages/yelp-xsl/SPECS/yelp-xsl.spec
Forgot the update to sgug-rpm-tools that has "sgugshell" in the minimal ball.
This pull request pulls that change into the 0.0.7 set.
=> Wipnonautomated

packages/glib2/SOURCES/glib2.sgifixes.patch, packages/glib2/SPECS/glib2.spec, packages/libsmartcols/SPECS/libsmartcols.spec, packages/libsolv/SOURCES/libsolv.sgifixes.patch, packages/libsolv/SPECS/libsolv.spec, packages/microdnf/SPECS/microdnf.spec, packages/sgug-rpm-tools/SPECS/sgug-rpm-tools.spec, packages/sgugrse-release/SPECS/sgugrse-release.spec, packages/sgugrse-repos/SOURCES/sgugrse-updates-testing.repo, packages/sgugrse-repos/SOURCES/sgugrse-updates.repo, packages/sgugrse-repos/SOURCES/sgugrse.repo, packages/sgugrse-repos/SPECS/sgugrse-repos.spec
Ensure we have libiconv, openssh-clients + sgugrse-repos in the minimal ball (sgug-rpm-tools)
Fix the formatting of package sizes in microdnf with fix in glib2
Ensure microdnf requires glib2-fam for directory/file monitoring
Bug fix to libsmartcols typo.
=> Further clean up tweaks for 0.0.7beta + microdnf

packages/sgug-rpm-config/SOURCES/macros.ldconfig, packages/sgug-rpm-config/SPECS/sgug-rpm-config.spec
This restores macros.d/macros.ldconfig , but only runs 'echo' when invoked.
Tested to not interfere with builds.
=> Shim to quietly skip ldconfig-type  macros in specs during rpmbuild

packages/openssh/SOURCES/openssh.sgifixes2.patch, packages/openssh/SOURCES/sgug-sshd, packages/openssh/SPECS/openssh.spec
This fixes:
- sshd_config to remove PAM etc references, so that sshd successfully comes up 
- adds an entry to /etc/init.d called `sgug-sshd`, as well as a `chkconfig` flag
- if the flag doesn't exist, it's set to on by default and sgug-sshd is started (just like it would be on linux)
- removes some stuff from the rpm that shouldn't bein there (systemd units/scripts)
- 
The file in /etc is created as symlinks to a file in /usr/sgug by the postinst script; the rpm itself doesn't contain any files that go to /etc.
=> Fix up openssh-server to automatically set itself up

packages/keychain/SPECS/keychain.spec
Add the keychain package.  This is a useful package that manages ssh agent authorization in multiple terminals/tmux sessions/etc.
=> Add keychain package

packages/gdb/SOURCES/gdb.elfirix.patch, packages/gdb/SPECS/gdb.spec
gdb wasn't recognizing elf binaries with ELFOSABI_IRIX to actually be IRIX
=> Fix gdb to recognize ELFOSABI_IRIX

packages/tdnf/SOURCES/tdnf-no-dlclose-plugins.patch, packages/tdnf/SPECS/tdnf.spec
Fixes gpg plugin atexit crash.
=> Don't dlclose plugins, as some may have atexit handlers

troubleshooting.md
I'm proposing this change to the sudo instructions. Using sudoers file has advantages:
- It's simpler to do and less dangerous (less chance of messing up an important system file)
- It stays contained in the /usr/sgug environment
- It doesn't require to modify the user groups, which might not always be desirable
- It offers more granularity if wanted
- It allows to set the timeout between two passwords, which is great considering that the default is 30 seconds
=> Improved sudo instructions

packages/sgugshell/SOURCES/sgugshell
EG for nedit to open a file on double click from fm when `/usr/sgug/bin/sgugshell nedit` is set as `Desktop >> Customize >> Utilities` text editor.
=> Exec should pass following arguments (after cmd) along
