- README.md
- packages/libmikmod/SPECS/libmikmod.spec
- packages/libmikmod/SPECS/libmikmod.spec.origfedora
- packages/make/SPECS/make.spec
- packages/mikmod/SPECS/mikmod.spec
- packages/mikmod/SPECS/mikmod.spec.origfedora
- packages/openssh/SPECS/openssh.spec
- sgugshell.sh
Needed to get the tag in the right place.
> Updates for v0.0.4beta

- packages/sudo/SPECS/sudo.spec
Ensure dep on vim-minimal so that rse minimal tarball visudo has an editor. fixes #29
> sudo - depend on vim-minimal.

- packages/pcre/SOURCES/pcre0843.irix.patch
- packages/pcre/SPECS/pcre.spec
- packages/pcre/SPECS/pcre.spec.origfedora
Note I removed one test that seems to fail for IRIX.
> added pcre

- packages/libuv/SOURCES/libuv.sgifixes.patch
- packages/libuv/SPECS/libuv.spec
- packages/libuv/SPECS/libuv.spec.origfedora
builds + many tests passing. no file monitoring events + still some bugs in the pipe/networking code.
> libuv: first import

- packages/cairo/SPECS/cairo.spec
- packages/gobject-introspection/SPECS/gobject-introspection.spec
- packages/libimagequant/SPECS/libimagequant.spec
- packages/libxnm/SPECS/libxnm.spec
- packages/pango/SPECS/pango.spec
- packages/python3-markdown/SPECS/python-markdown.spec
- packages/xorg-x11-utils/SPECS/xorg-x11-utils.spec
> Changelog fixes

- packages/aspell/SOURCES/aspell-0.60.7-fileconflict.patch
- packages/aspell/SOURCES/aspell-0.60.7-mp.patch
- packages/aspell/SOURCES/aspell-0.60.7-pspell_conf.patch
- packages/aspell/SPECS/aspell.spec
- packages/chrpath/SPECS/chrpath.spec
chrpath: [build + install log](https://gist.github.com/mach-kernel/8d68deb275cdc94d343761aab520f151)
> chrpath + aspell

- packages/malaga-suomi-voikko/SPECS/malaga-suomi-voikko.spec
- packages/malaga/SOURCES/malaga-aarch64.patch
- packages/malaga/SOURCES/malaga-cell.patch
- packages/malaga/SOURCES/malaga-malshow-lm.patch
- packages/malaga/SOURCES/malaga-rename-map_file.diff
- packages/malaga/SPECS/malaga.spec
**malaga**
[Build log](https://gist.github.com/mach-kernel/aa5cfa44f64527af6d4b24f3558bc719)
```
1:libmalaga-7.12-29.sgugbeta       ################################# [100%]
[sgugshell mach@octane packages]$ sudo rpm -ivh ~/rpmbuild/RPMS/mips/malaga-*.rpm
1:malaga-devel-7.12-29.sgugbeta    ################################# [ 50%]
2:malaga-7.12-29.sgugbeta          ################################# [100%]
``` …
> Add malaga

- packages/libvoikko/SPECS/libvoikko.spec
[Build log](https://gist.github.com/mach-kernel/636e54596f87c04154c20e017d3b5489)
> Add libvoikko

- README.md
- helperscripts/copyback.pl
- packages/pixman/SPECS/pixman.spec
ncargs tweak (mention in README.md) and fix pixman to avoid building gtk demos.
> More tweaks to get 0.0.6prerelease building

- packages/abattis-cantarell-fonts/SPECS/abattis-cantarell-fonts.spec
- packages/abattis-cantarell-fonts/SPECS/abattis-cantarell-fonts.spec.origfedora
- packages/fontpackages/SOURCE/perl.irixfixes.patch
- packages/fontpackages/SPECS/fontpackages.spec.origfedora
- packages/pango/SOURCES/pango.sgifixes.patch
- packages/pango/SPECS/pango.spec
- packages/redhat-rpm-config/SOURCES/brp-mangle-shebangs
- packages/redhat-rpm-config/SPECS/redhat-rpm-config.spec
- releasepackages.lst
> Font work (getting more pango tests passing + new font)

- packages/groff/SPECS/groff.spec
- packages/redhat-rpm-config/SOURCES/brp-mangle-shebangs
- packages/redhat-rpm-config/SPECS/redhat-rpm-config.spec
Some more tweaks for problems discovered during 0.0.6 rebuilds.
Hopefully the last!
> Final changes discovered during the 0.0.6 rebuilds

- README.md
And let's update the README to talk about 0.0.6 now it's a thing.
> README.md: update to refer to 0.0.6 artefacts

- packages/barrier/SOURCES/barrier.sgifixes.patch
- packages/barrier/SPECS/barrier.spec
- packages/barrier/SPECS/barrier.spec.origfedora
Testing, testing 123. What is proper procedure here sarge?
> Barrier wip

- packages/libmetalink/SOURCES/libmetalink-0.1.3-ns_uri.patch
- packages/libmetalink/SPECS/libmetalink.spec
```
Checking for unpackaged file(s): /usr/sgug/lib/rpm/check-files /usr/people/mach/rpmbuild/BUILDROOT/libmetalink-0.1.3-14.sgug.mips
Wrote: /usr/people/mach/rpmbuild/SRPMS/libmetalink-0.1.3-14.sgug.src.rpm
Wrote: /usr/people/mach/rpmbuild/RPMS/mips/libmetalink-0.1.3-14.sgug.mips.rpm
Wrote: /usr/people/mach/rpmbuild/RPMS/mips/libmetalink-devel-0.1.3-14.sgug.mips.rpm
Executing(%clean): /usr/sgug/bin/sh -e /usr/sgug/var/tmp/rpm-tmp.096761
+ umask 022
+ cd /usr/people/mach/rpmbuild/BUILD
+ cd libmetalink-0.1.3
+ /usr/sgug/bin/rm -rf /usr/people/mach/rpmbuild/BUILDROOT/libmetalink-0.1.3-14.sgug.mips
+ RPM_EC=0
+ jobs -p
+ exit 0
```
> Add libmetalink

- packages/sgugshell/SOURCES/sgugshell
> J16bit sgugshell improvement

- packages/netsurf/SOURCES/netsurf-all-3.10.sgifixes.patch
- packages/netsurf/SPECS/netsurf.spec
debug logging no longer required
> J16bit netsurf 3 10 touchups

- packages/hexchat/SPECS/hexchat.spec
- packages/hexchat/SPECS/hexchat.spec.origfedora
> J16bit hexchat

- README.md
- contributing.md
- packages/mpg123/SPECS/mpg123.spec
Fixed missing output_sgi plug-in in %files.
Fixes rpmbuild and closes #195
> mpg123 added missing file

- packages/alpine/SOURCES/alpine-2.24-sgifixes.patch
- packages/alpine/SPECS/alpine.spec
- packages/alpine/SPECS/alpine.spec.origfedora
Builds cleanly, tested and works fine with IMAP / SMTP accounts.
> Alpine 2.24 1.fc31

- packages/jq/SPECS/jq.spec
- packages/jq/SPECS/jq.spec.origfedora
- packages/oniguruma/SPECS/oniguruma.spec
- packages/yad/SPECS/yad.spec
- packages/yad/SPECS/yad.spec.original
Lets be honest, jq is all that matters here
> J16bit youtube gui bits

- packages/avfs/SOURCES/worker.sgifixes.patch
- packages/avfs/SPECS/avfs.spec
- packages/avfs/SPECS/avfs.spec.orig
- packages/worker/SPECS/worker.spec
Adding AVFS package & support to worker.
Also disabling Worker from looking for dbus.
> Adding AVFS package & support to worker.

- packages/icebreaker/SOURCES/icebreaker.sgifixes.patch
- packages/icebreaker/SPECS/icebreaker.spec
- packages/icebreaker/SPECS/icebreaker.spec.orig
It's in nekoware and I wanna play it, build with minimal fuss. SRPM sourced from their own website, not in FC31.
> Add icebreaker game

- packages/netsurf/SPECS/netsurf-motif.spec
- packages/netsurf/SPECS/netsurf.spec
> Minor version bumps
